# CREDITS

## Fonts

* https://www.dafont.com/sector-017.font by Neoqueto
* https://www.dafont.com/electronic-highway-sign.font by Ash Pikachu Font
* https://www.dafont.com/tidy-hand.font Sean Johnson

## Sound effects

All sound effects are generated by [sfxr](https://www.drpetter.se/project_sfxr.html) (by drpetter).

## Music

Seven(New Music Remix) by bwatts (c) copyright 2012
Licensed under a Creative Commons Attribution (3.0) license.
http://dig.ccmixter.org/files/bwatts/39793 Ft: alex beroza (bwatts)
